version: "3.9"

services:

  waha:
    container_name: waha-plus
    image: devlikeapro/waha-plus:latest
    restart: always
    ports:
      - "${WAHA_PORT}:${WAHA_PORT}"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./sessions:/app/.sessions
    networks:
      - waha-network

  redis:
    container_name: waha-redis
    image: redis:7-alpine
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - waha-network


networks:
  waha-network:
    driver: bridge


volumes:
  redis_data: